spring.application.name=demo

spring.datasource.username=root
spring.datasource.password=bf7mUw1BdfwuwWTe2o85L74h
spring.datasource.url=jdbc:mariadb://ovh2.cloud.layerbase.dev:23338/webboard?sslMode=trust
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
